CREATE SCHEMA IF NOT EXISTS mainphotos;

CREATE TABLE mainphotos.neighborhoods (
  neighborhood_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  neighborhood_name VARCHAR(50) NOT NULL
);

CREATE TABLE mainphotos.property_listings (
  listing_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  neighborhood INT NOT NULL REFERENCES mainphotos.neighborhoods( neighborhood_id ) ON DELETE RESTRICT,
  address VARCHAR(100) NOT NULL,
  pricing DECIMAL(100,2) NOT NULL,
  bedrooms DECIMAL(3,1) NOT NULL,
  baths DECIMAL(3,1) NOT NULL,
  sq_footage INT NOT NULL
);

CREATE TABLE mainphotos.image_urls (
  image_id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  url VARCHAR(50) NOT NULL
);

CREATE TABLE mainphotos.property_images (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  listing_id INT NOT NULL REFERENCES mainphotos.property_listings(listing_id) ON DELETE CASCADE,
  image_id INT NOT NULL REFERENCES mainphotos.image_urls(image_id) ON DELETE RESTRICT
);

CREATE TABLE mainphotos.price_history (
  listing_id INT NOT NULL PRIMARY KEY REFERENCES mainphotos.property_listings(listing_id) ON DELETE CASCADE,
  event_date date NOT NULL,
  event_description VARCHAR(30) NOT NULL,
  price DECIMAL(100, 2) NOT NULL
);

CREATE TABLE mainphotos.status (
  listing_id INT NOT NULL PRIMARY KEY REFERENCES mainphotos.property_listings(listing_id) ON DELETE CASCADE,
  sale BOOLEAN DEFAULT false NOT NULL,
  pending BOOLEAN DEFAULT false NOT NULL,
  new BOOLEAN DEFAULT false NOT NULL,
  construction BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE mainphotos.crimes (
  crime_id INT PRIMARY KEY,
  neighborhood_id INT NOT NULL REFERENCES mainphotos.neighborhoods( neighborhood_id ) ON DELETE CASCADE,
  type VARCHAR(20) NOT NULL,
  crime_title VARCHAR(20) NOT NULL,
  description VARCHAR(100) NOT NULL
);

CREATE TABLE mainphotos.schools(
  school_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  address VARCHAR(100) NOT NULL
);

CREATE TABLE mainphotos.neighborhood_schools (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  school_id INT NOT NULL REFERENCES mainphotos.schools(school_id) ON DELETE RESTRICT,
  neighborhood_id INT NOT NULL REFERENCES mainphotos.neighborhoods( neighborhood_id ) ON DELETE CASCADE
);
CREATE TABLE mainphotos.businesses (
  business_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  type VARCHAR(20) NOT NULL,
  name VARCHAR(30) NOT NULL,
  address VARCHAR(100) NOT NULL
);

CREATE TABLE mainphotos.neighborhood_businesses (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  business_id INT NOT NULL REFERENCES mainphotos.businesses(business_id) ON DELETE RESTRICT,
  neighborhood_id INT NOT NULL REFERENCES mainphotos.neighborhoods( neighborhood_id ) ON DELETE CASCADE
);